# Numpy Review

In [15]:
import numpy as np
print("Numpy Version:", np.__version__)

Numpy Version: 1.15.1


In [3]:
#numpy array:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr = np.arange(10)

In [5]:
?arr

In [7]:
#built in methods
arr.mean()

4.5

In [8]:
arr.sum()

45

In [10]:
arr.std()

2.8722813232690143

In [17]:
#with python functions we can use list comprehension or built in and anonymous functionsw with numpy arrays

In [12]:
#numpy arrays can be iterated through just like lists:
[i * i for i in arr]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [25]:
#map + lambda:
print(list(map(lambda i: i**2, arr)))
print(list(filter(lambda i: i%2 == 0,arr)))
print(list(map(lambda i: i**3, filter(lambda i: i%2 == 0, arr))))

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
[0, 2, 4, 6, 8]
[0, 8, 64, 216, 512]


In [26]:
#we can do the same directly on numpy array:
arr % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [28]:
arr[arr%2==0]

array([0, 2, 4, 6, 8])

In [27]:
list(arr % 2 == 0)

[True, False, True, False, True, False, True, False, True, False]

In [32]:
new_arr = np.arange(10000)

In [33]:
#list comprehension is slower:
%timeit [i for i in new_arr if i % 2 == 0]

5.7 ms ± 136 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [34]:
#Boolean selection is fastest:
%timeit new_arr[new_arr % 2 == 0]

243 µs ± 4.39 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [35]:
npa = np.arange(20)

In [38]:
#select everything that is greater than 10:
npa[npa > 10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [40]:
#Boolean Selection over npa numpy array
(npa > 15) | (npa < 12)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False, False, False,  True,  True,
        True,  True])

In [43]:
npa[(npa > 12)&(npa<14)]

array([13])

In [54]:
#Create array of True False values:
npp = np.array(list(True for i in range(20)))
#could have done this too:
# >> npp = np.array([True for i in range(20)])

In [55]:
npp

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [61]:
type(npp)

numpy.ndarray

In [57]:
#dtype command can tell us which data types are the objects inside the array
npp.dtype

dtype('bool')

In [62]:
np.array(range(30))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [63]:
np.array([1.0,2.0]).dtype

dtype('float64')

In [64]:
#coerce numbers into true false booleans
np.array([True, 0,2], dtype="bool_")

array([ True, False,  True])

In [66]:
#coerce boolean values into numbers
np.array([True, 0,2], dtype="uint8")

array([1, 0, 2], dtype=uint8)

In [68]:
print(npp.size)
print(npp.shape)

20
(20,)


In [72]:
print(npp.min(),npp.max())

True True


In [77]:
#initialization of array with step
print(np.arange(1,100,20))
print(np.arange(1,-100, -20))
print(np.arange(100,0,-20))

[ 1 21 41 61 81]
[  1 -19 -39 -59 -79 -99]
[100  80  60  40  20]


In [86]:
#linspace creates array with n values equally distance in range defined:
print(np.linspace(1,10,5))
print(np.linspace(100,10,5))
print('---')
print(np.linspace(100,1000, 55))
print('---')
print(np.linspace(100,1000, 55).astype('int'))
print('---')
print(np.linspace(100,1000, 55).astype(np.int))

[ 1.    3.25  5.5   7.75 10.  ]
[100.   77.5  55.   32.5  10. ]
---
[ 100.          116.66666667  133.33333333  150.          166.66666667
  183.33333333  200.          216.66666667  233.33333333  250.
  266.66666667  283.33333333  300.          316.66666667  333.33333333
  350.          366.66666667  383.33333333  400.          416.66666667
  433.33333333  450.          466.66666667  483.33333333  500.
  516.66666667  533.33333333  550.          566.66666667  583.33333333
  600.          616.66666667  633.33333333  650.          666.66666667
  683.33333333  700.          716.66666667  733.33333333  750.
  766.66666667  783.33333333  800.          816.66666667  833.33333333
  850.          866.66666667  883.33333333  900.          916.66666667
  933.33333333  950.          966.66666667  983.33333333 1000.        ]
---
[ 100  116  133  150  166  183  200  216  233  250  266  283  300  316
  333  350  366  383  400  416  433  450  466  483  500  516  533  550
  566  583  600  616  633  6

In [88]:
#nan is null value in numpy:
ar = np.linspace(0,10,11).astype(np.float32)

In [89]:
ar

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
      dtype=float32)

In [90]:
ar[0] = np.nan

In [91]:
#now we have nan value
ar

array([nan,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
      dtype=float32)

In [92]:
#nan can throw off calculations:
print(ar.min())
print(ar.max())

nan
nan


/Users/pauldefusco/anaconda2/envs/py36/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: invalid value encountered in reduce
  return umr_minimum(a, axis, None, out, keepdims, initial)
/Users/pauldefusco/anaconda2/envs/py36/lib/python3.6/site-packages/numpy/core/_methods.py:28: RuntimeWarning: invalid value encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims, initial)


#### Vectorization:

Allows to perform computation on entire dataset rather than by iteration

In [96]:
#create 20 values between 0 and 50, randomly:
npa = np.random.randint(0,50,20)

In [97]:
npa

array([20, 21, 21, 37, 49,  5, 43, 37, 23, 44, 11, 33, 15, 41, 43, 25, 46,
       27, 32, 45])

In [98]:
#typical approach:
#LC:
print([i*2 for i in npa])
#built in functions:
print(list(map(lambda i: i*2, npa)))

[40, 42, 42, 74, 98, 10, 86, 74, 46, 88, 22, 66, 30, 82, 86, 50, 92, 54, 64, 90]
[40, 42, 42, 74, 98, 10, 86, 74, 46, 88, 22, 66, 30, 82, 86, 50, 92, 54, 64, 90]


In [100]:
#Vectorization: treating the entire array as a single value:
#notice the object returned is an array:
npa * 2

array([40, 42, 42, 74, 98, 10, 86, 74, 46, 88, 22, 66, 30, 82, 86, 50, 92,
       54, 64, 90])

In [101]:
def new_f(num):
    if num < 10:
        return num ** 2
    else:
        return num ** 3

In [105]:
new_f(npa)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [102]:
?np.vectorize

In [103]:
#create vectorized version of function that will allow to compute on entire array:
vnew = np.vectorize(new_f)

In [104]:
#now it works, and it's also a lot faster:
vnew(npa)

array([  8000,   9261,   9261,  50653, 117649,     25,  79507,  50653,
        12167,  85184,   1331,  35937,   3375,  68921,  79507,  15625,
        97336,  19683,  32768,  91125])

Performance comparisons:

In [111]:
npa2 = np.random.randint(0,100,100000)

In [112]:
#unvectorized
%timeit [new_f(i) for i in npa2]

95.3 ms ± 2.82 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [113]:
#vectorized
%timeit vnew(npa2)

82.4 ms ± 1.46 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


### Multidimensional Arrays

In [114]:
npa = np.arange(25)
npa.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [115]:
#now passing a tuple:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [117]:
print(npa.shape)
print(npa.size)
print(npa.ndim)

(25,)
25
1


In [118]:
print(np.arange(8).reshape(2,2,2))

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [120]:
np.arange(100).reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [122]:
#setting seed allows to generate similar or duplicate random generators
np.random.seed(10)
np.random.randint(1,10,25)

array([5, 1, 2, 1, 2, 9, 1, 9, 7, 5, 4, 1, 5, 7, 9, 2, 9, 5, 2, 4, 7, 6,
       4, 7, 2])

In [123]:
np.random.randint(1,20,25)

array([ 5, 19, 14, 12, 11, 10, 16, 19, 17,  8, 12, 18, 15,  8, 12,  2,  1,
       13,  6,  5,  8, 19, 13,  3,  9])

In [124]:
#but if we set the seed again, we will have the same result:
np.random.seed(10)
np.random.randint(1,20,25)

array([10,  5, 16,  1, 18, 17, 18,  9, 10,  1, 11,  9,  5, 17,  5, 16, 12,
       12,  2,  9,  5, 15, 18, 14,  6])

In [125]:
np.random.seed(10)
np.random.randint(1,20,25)

array([10,  5, 16,  1, 18, 17, 18,  9, 10,  1, 11,  9,  5, 17,  5, 16, 12,
       12,  2,  9,  5, 15, 18, 14,  6])

In [128]:
(np.random.randint(1,20,25) > np.random.randint(1,20,25)).sum()

10

In [132]:
np.random.randint(1,20,25).reshape(5,5)

array([[ 9, 14,  4,  1,  9],
       [14, 19, 16, 10,  1],
       [13, 18, 11, 13, 16],
       [15, 12,  8,  4, 16],
       [15,  3,  5,  5,  1]])

In [134]:
np.random.randint(1,20,25).reshape(5,5).max() == np.random.randint(1,20,25).max()

True

In [136]:
A = np.random.randint(1,20,25).reshape(5,5)

In [137]:
#Transpose:
A == A.T

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False],
       [False, False, False, False,  True]])

In [138]:
#make A nx1
A.flatten()

array([ 4, 10, 18,  3,  5, 14, 15, 17,  9,  3,  4, 14, 10,  5,  5,  9, 19,
        2,  7, 15,  9,  8, 17,  6,  3])

In [139]:
#ravel: does the same but returns
A.ravel()

array([ 4, 10, 18,  3,  5, 14, 15, 17,  9,  3,  4, 14, 10,  5,  5,  9, 19,
        2,  7, 15,  9,  8, 17,  6,  3])

In [140]:
A.flatten()[0] = 25

In [141]:
A

array([[ 4, 10, 18,  3,  5],
       [14, 15, 17,  9,  3],
       [ 4, 14, 10,  5,  5],
       [ 9, 19,  2,  7, 15],
       [ 9,  8, 17,  6,  3]])

In [142]:
A.ravel()[0] = 25

In [143]:
#this time the change has been made:
A

array([[25, 10, 18,  3,  5],
       [14, 15, 17,  9,  3],
       [ 4, 14, 10,  5,  5],
       [ 9, 19,  2,  7, 15],
       [ 9,  8, 17,  6,  3]])

In [144]:
#adds each value to the previous value
#cumulative running sum
A.cumsum()

array([ 25,  35,  53,  56,  61,  75,  90, 107, 116, 119, 123, 137, 147,
       152, 157, 166, 185, 187, 194, 209, 218, 226, 243, 249, 252])

In [145]:
#Cumulative product:
A.cumprod()

array([                  25,                  250,                 4500,
                      13500,                67500,               945000,
                   14175000,            240975000,           2168775000,
                 6506325000,          26025300000,         364354200000,
              3643542000000,       18217710000000,       91088550000000,
            819796950000000,    15576142050000000,    31152284100000000,
         218065988700000000,  3270989830500000000, -7454579672919103232,
       -4296405162224171008,   748088537027299328,  4488531222163795968,
       -4981150407218163712])

#### Slicing and Querying Arrays

In [155]:
np.random.seed(10)

In [162]:
ar = np.random.randint(2,5,5)

In [159]:
ar2 = np.random.randint(12, size=12)

In [161]:
ar3 = np.random.randint(12, size=(3,4))

In [164]:
ar2[5]

1

In [165]:
ar2[2:]

array([ 8, 11, 10,  1,  8,  4,  1,  3,  6,  5])

In [167]:
ar2[1:12:2]

array([ 6, 11,  1,  4,  3,  5])

In [168]:
#All rows, first and second column:
ar3[:,1:3]

array([[9, 6],
       [9, 4],
       [6, 7]])

In [170]:
ar3[:,1:4]

array([[ 9,  6,  9],
       [ 9,  4, 11],
       [ 6,  7,  8]])

In [181]:
#Three Dimensional Arrays:
ar4 = np.random.randint(30, size=(5,3,2))

In [184]:
#Querying 3 D array: first item in 1d, all items in 2d, first and second items in 3d
ar4[1:2,:,1:3]

array([[[ 5],
        [13],
        [18]]])

In [198]:
ar5 = np.random.randint(1,12, size=10)
ar6 = np.random.randint(1100, size=10)

In [200]:
ar5

array([ 2,  8,  2,  2, 11,  6,  6,  1, 11,  9])

In [202]:
ar6

array([515, 925, 453,   5, 710, 189, 232, 714, 644, 918])

In [206]:
#creates 2 D array by stacking original arrays
np.vstack((ar5,ar6))

array([[  2,   8,   2,   2,  11,   6,   6,   1,  11,   9],
       [515, 925, 453,   5, 710, 189, 232, 714, 644, 918]])

In [207]:
#merges arrays into one
np.hstack((ar5,ar6))

array([  2,   8,   2,   2,  11,   6,   6,   1,  11,   9, 515, 925, 453,
         5, 710, 189, 232, 714, 644, 918])

In [208]:
#same as hstack:
np.concatenate((ar5,ar6))

array([  2,   8,   2,   2,  11,   6,   6,   1,  11,   9, 515, 925, 453,
         5, 710, 189, 232, 714, 644, 918])

In [210]:
twod_ar1 = np.random.randint(10, size=10).reshape(2,5)
twod_ar2 = np.random.randint(10, size=10).reshape(2,5)

In [215]:
#now with 2 D arrays:
np.concatenate((twod_ar1, twod_ar2))

array([[5, 9, 3, 8, 3],
       [0, 9, 6, 2, 3],
       [9, 1, 4, 0, 5],
       [0, 8, 1, 3, 6]])

In [216]:
#axis gives axis of contatenation
np.concatenate((twod_ar1, twod_ar2), axis=1)

array([[5, 9, 3, 8, 3, 9, 1, 4, 0, 5],
       [0, 9, 6, 2, 3, 0, 8, 1, 3, 6]])

In [219]:
#vertical concatenation (default)
np.concatenate((twod_ar1, twod_ar2), axis=0)

array([[5, 9, 3, 8, 3],
       [0, 9, 6, 2, 3],
       [9, 1, 4, 0, 5],
       [0, 8, 1, 3, 6]])

In [220]:
ndim_ar3d_stack = np.dstack((twod_ar1, twod_ar2))

In [221]:
ndim_ar3d_stack

array([[[5, 9],
        [9, 1],
        [3, 4],
        [8, 0],
        [3, 5]],

       [[0, 0],
        [9, 8],
        [6, 1],
        [2, 3],
        [3, 6]]])

In [223]:
ar2

array([11,  6,  8, 11, 10,  1,  8,  4,  1,  3,  6,  5])

In [224]:
#chop array into two, horizontally:
np.hsplit(ar2, 2)

[array([11,  6,  8, 11, 10,  1]), array([8, 4, 1, 3, 6, 5])]

In [231]:
ar3.shape

(3, 4)

In [232]:
ar2.shape

(12,)

In [230]:
np.vsplit(np.concatenate((ar2.reshape(3,4), ar3)),2)

[array([[11,  6,  8, 11],
        [10,  1,  8,  4],
        [ 1,  3,  6,  5]]), array([[ 3,  9,  6,  9],
        [ 1,  9,  4, 11],
        [ 2,  6,  7,  8]])]