In [1]:
import math
import matplotlib.pyplot as plt
%pylab inline
import numpy as np
from sklearn import datasets
iris = datasets.load_iris()
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(iris.data, iris.target)

print gnb.class_count_
print gnb.class_prior_
print gnb.sigma_

Populating the interactive namespace from numpy and matplotlib
[ 50.  50.  50.]
[ 0.33333333  0.33333333  0.33333333]
[[ 0.121764  0.142276  0.029504  0.011264]
 [ 0.261104  0.0965    0.2164    0.038324]
 [ 0.396256  0.101924  0.298496  0.073924]]


In [2]:
y_pred = gnb.predict(iris.data)
print("Number of mislabeled points out of a total %d points : %d" % (iris.data.shape[0],(iris.target != y_pred).sum()))

Number of mislabeled points out of a total 150 points : 6


In [4]:
#mean = np.array(examples.mean(0))[0]
#cov = np.cov(examples, rowvar=0)
#p_x = multivariate_normal(mean=mean, cov=cov)

#For iris dataset we will have 4x4 
#covariance matrix b/c there are 4 features in our training set., 
#here’s an example of finding the covariance matrix ΣΣ on the iris 
#trainging set. We should be abel to confirm our answer

#lets split into a test and training set
from sklearn.cross_validation import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(iris.data,iris.target, test_size=0.4, random_state=4)

# lets gather all the examples from class 0
def get_examples_for_class(class_id):
    examples = []
    for i, example in enumerate(X_train):
        if Y_train[i]==class_id:
            examples.append(example)
        
    examples = np.matrix(examples)
    return examples

examples = get_examples_for_class(0)
examples.shape

/Users/pauldefusco/anaconda2/lib/python2.7/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


(25, 4)

In [5]:
mean = np.array(examples.mean(0))[0]
cov = np.cov(examples.T) # I don't know why you have to transpose the input to numpy... 
print mean
print cov

[ 4.964  3.416  1.44   0.24 ]
[[ 0.1049      0.06976667  0.01483333  0.00566667]
 [ 0.06976667  0.10723333  0.00391667  0.00266667]
 [ 0.01483333  0.00391667  0.02583333  0.00625   ]
 [ 0.00566667  0.00266667  0.00625     0.01      ]]


In [6]:
from scipy.stats import multivariate_normal
P_0 = np.random.multivariate_normal(mean, cov).T
P_0

var = multivariate_normal(mean=mean, cov=cov)

In [41]:
prob_0

[0, 1.2060594131871579e-172]

In [9]:
X1=X_test[15]
import random
X1 = random.choice (X_test)
print X1
prior = pi_0 = gnb.class_prior_[0]
prob_0=[0, var.pdf(X1)]

#now for class 1
examples_1 = get_examples_for_class(1)
mean_1 = np.array(examples_1.mean(0))[0]
cov_1 = np.cov(examples_1.T)
p_x_1 = multivariate_normal(mean=mean_1, cov=cov_1)
prob_1 = [1, gnb.class_prior_[1] * p_x_1.pdf(X1)]

#now for class 2
examples_2 = get_examples_for_class(2)
mean_2 = np.array(examples_2.mean(0))[0]
cov_2 = np.cov(examples_2.T)
p_x_2 = multivariate_normal(mean=mean_2, cov=cov_2)
prob_2 = [2, gnb.class_prior_[2] * p_x_2.pdf(X1)]

prediction = max(prob_0, prob_1, prob_2, key= lambda a: a[1])
print iris.target_names[prediction[0]]

X = iris.data
Y = iris.target
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()
clf.fit(X, Y)

print(iris.target_names[clf.predict([X1])][0])


[ 6.4  2.8  5.6  2.2]
virginica
virginica


In [37]:
p_x_2

In [10]:
digits = datasets.load_digits()
X_train, X_test, Y_train, Y_test = train_test_split(digits.data, digits.target, test_size=0.4, random_state=4)
X_train.shape

(1078, 64)

In [11]:
helper = GaussianNB()
helper.fit(X_train, Y_train)
classes = helper.classes_
priors = helper.class_prior_
print classes
priors

[0 1 2 3 4 5 6 7 8 9]


array([ 0.09369202,  0.10482375,  0.0974026 ,  0.0974026 ,  0.10575139,
        0.10296846,  0.0974026 ,  0.10018553,  0.09925788,  0.10111317])

In [30]:
#from numpy.random import multivariate_normal
#, allow_singular=True
from scipy.stats import multivariate_normal
posteriors=[]

for klass in classes:
    examples = get_examples_for_class(klass)
    mean = np.array(examples.mean(0))[0]
    cov = np.cov(examples.T)
    p_x = multivariate_normal(mean=mean, cov=cov, allow_singular=True)
    posteriors.append(p_x)

In [31]:
posteriors

In [16]:
x = random.choice (X_test)
print x

[  0.   0.   2.  15.   4.   0.   0.   0.   0.   0.  11.  13.   0.   0.   0.
   0.   0.   0.  16.   6.   0.   0.   0.   0.   0.   3.  16.   7.   0.   0.
   0.   0.   0.   4.  16.  16.  15.   5.   0.   0.   0.   4.  16.   5.   3.
  13.   7.   0.   0.   1.  14.   9.   0.   8.  13.   0.   0.   0.   2.  13.
  16.  16.   8.   0.]


In [17]:
bayes_probs = []
for klass in classes:
    prob = [klass, priors[klass] * posteriors[klass].pdf(x)]
    bayes_probs.append(prob)
bayes_probs

[[0, 0.0],
 [1, 2.7404854530162325e-293],
 [2, 0.0],
 [3, 3.2697255389178208e-179],
 [4, 0.0],
 [5, 8.261074358167956e-157],
 [6, 3.1125128442032229e-37],
 [7, 0.0],
 [8, 4.2275219511188878e-83],
 [9, 1.7091942811817822e-251]]

In [24]:
posteriors